site_name: PPS Unidad 1 - Jesus Sanchez
nav:
  - Inicio: index.md

theme:
  name: material
  language: es
  palette:
  # Modo Oscuro
    - scheme: slate #Por defecto
      primary: black # Color del header
      accent: lime # Color de los enlaces y botones al pasar el ratón por encima
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    # Modo Claro 
    - scheme: default
      primary: indigo   
      accent: purple   
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

  features:
    - navigation.top  # Botón para volver arriba
    - navigation.expand  # Hace que el menú de la izquierda salga abierto

plugins:
  - search #Buscador
  - glightbox #Para poder poner las imagenes en pantalla completa
  
markdown_extensions:
  - admonition # Extension para las cajas de warning, info,etc
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
 
extra_css:
  - stylesheets/extra.css # Css personalizado que modifica las imagenes para que tengan borde y sombra

